### ISSUE TITLE
Opening this repo's page causes gitit to crash

### ISSUE THREAD

**Issue by ben-zen** [prajjwaldimri/GithubXamarin#50]
I'm using a 950, running a fast insider build, in FR-CA. Searching for GithubXamarin and then tapping on the repo causes gitit to crash.

**Comment by ben-zen** [comment]
Correction! Opening *any* repo from the search page causes a crash. I really should test additional scenarios before opening an issue.

**Comment by prajjwaldimri** [comment]
@ben-zen Thanks for reporting the issue. It is happening because of the code on lines 133,134,135  in SearchViewModel. I forgot to change the type of MvxCommand to object so it is having errors converting WindowsClickEventArgs to Octokit's objects. I will push a update with live tile support tonight and this will be fixed on that update.

**Comment by ben-zen** [comment]
Awesome, thank you.
